name: Prek Autoupdate Schedule

on:
    schedule:
        # Run at 03:00 every Monday
        - cron: "0 3 * * 1"
    workflow_dispatch:
        # Allow manual triggering

jobs:
    prek-autoupdate:
        permissions:
            contents: write
            pull-requests: write
        uses: emmet02/actions/.github/workflows/prek-autoupdate.yml@main
        with:
            branch_name: "bot/prek-autoupdate"
